version: '3.8'

services:
  database:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: ${POSTGRES_CONTAINER_NAME}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./pglogs:/logs
    ports:
      - '${POSTGRES_PORT}:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${DOCKER_ID}/home-library-service
    container_name: home-library-service
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - database
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules

networks:
  nest-service-network:
    driver: bridge
